### PR TITLE
Add x-checker-data

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by alastortenebris** [comment]
Seems to have worked.

**Comment by tsdgeos** [comment]
i think kimageformats should really be in the runtime

It's not only gwenview that can benefit from opening more kinds of images.

**Comment by alastortenebris** [comment]
> i think kimageformats should really be in the runtime
> 
> It's not only gwenview that can benefit from opening more kinds of images.

Agree. I know Dolphin uses it for thumbnails, and Okular as well. Having it in the runtime would simplify things tremendously.

**Comment by travier** [comment]
Make sense! Let's to that instead.

**Pull request merged**
