### PR TITLE
Update KDE runtime to 6.8, add phonon + backend

### PR DESCRIPTION
**Pull request by PunkPangolin**
Old ffmpeg is required for vlc to build and work properly.

### CODE REVIEW

**Comment by Erick555** [comment]
Note that using bundled ffmpeg means you won't have codec support for [heif](https://github.com/flathub/org.kde.gwenview/issues/158).

**Comment by Erick555** [comment]
The other way would be to duplicate codecs and loaders in app (and every similar app). Situation is really ugly. I don't know if forgetting about audio support isn't better.

**Comment by tsdgeos** [comment]
> Note that using bundled ffmpeg means you won't have codec support for https://github.com/flathub/org.kde.gwenview/issues/158.

Why?

**Comment by tsdgeos** [comment]
Merging because there's a different story with heif, needs more investigation kolourpaint can't open them either. I've checked and the heif plugin is there, but the open dialog doesn't offer them.

**Comment by travier** [comment]
Erick explained that in https://github.com/flathub/org.kde.okular/pull/387#issuecomment-2532806441

This is really unfortunate, we did not know about that when we took the decision for the 24.08 Runtime.

**Comment by travier** [comment]
I would vote for heif support over audio for Gwenview. It's more likely that images will be viewed in it than videos where we already have a lot of video players.

**Comment by tsdgeos** [comment]
That's a wrong explanation though, ffmpeg7 is still available because of the runtime and the heif image plugin still uses it.

Also as I said kolourpaint, that doesn't have ffmpeg4 can't open heif either (while the one from my distro can).

Let's figure out why kolourpaint can't open heif first and then let's worry about if heif works or not on gwenview.

**Comment by Erick555** [comment]
@tsdgeos for heif you need ffmpeg-full extension, I mentioned it [here](https://github.com/flathub/org.kde.gwenview/issues/158#issuecomment-2521243854)

Here's [example](https://github.com/flathub/org.kde.subtitlecomposer/blob/cd6031154e1694fdc72616aa4d2524dbb8592115/org.kde.subtitlecomposer.json#L29-L38) how to add it.

**Comment by Erick555** [comment]
ffmpeg situation is more nuanced. Your're right that heif should work regardless if app bundles ffmpeg or not because it comes from libheif (which is also part of ffmpeg-full) not ffmpeg.

The situation complicates when app use vlc and ffmpeg to play video with h264 or h265 codecs. Bundled ffmpeg won't support them without bundling the codecs as well. I don't know if kde have such app though. For phonon and heif it should work indeed as you said.

**Comment by Erick555** [comment]
I made PR for kolorpaint, you may test https://github.com/flathub/org.kde.kolourpaint/pull/99

**Pull request merged**
