### PR TITLE
Add cfitsio, libkdcraw & libkipi dependencies

### PR DESCRIPTION
**Pull request by travier**
See https://github.com/flathub/org.kde.gwenview/issues/1 for the remaining one.

### CODE REVIEW

**Comment by travier** [comment]
Hum, the intermediary cleanups are not taken into account.

**Comment by travier** [comment]
Never-mind, looks like they are.

**Comment by travier** [comment]
LGTM. Will merge at the end of the day.

**Comment by Erick555** [comment]
@travier you may add `*.la` files to cleanup.

**Comment by Erick555** [comment]
ping @travier @tsdgeos

**Comment by travier** [comment]
Tested that when posted so merging.

**Pull request merged**
